export const IDEMPOTENCY_KEY_MAX_LENGTH = 128;

export const CREATE_PAYMENT_IDEMPOTENCY_SCOPE = 'CREATE_PAYMENT';

export const IDEMPOTENCY_ERROR_CODE_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED';
export const IDEMPOTENCY_ERROR_CODE_VALIDATION = 'PAYMENT_VALIDATION_ERROR';
export const IDEMPOTENCY_ERROR_CODE_CONFLICT = 'PAYMENT_IDEMPOTENCY_CONFLICT';
